[package]
name = "tuack-lib"
description = "tuack-ng 后端公共逻辑库"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["tuack-ng", "oi", "acm", "contest"]
categories = ["development-tools"]

[dependencies]
anyhow.workspace = true
bytesize.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_many.workspace = true

[dependencies.tuack-ng-parser]
workspace = true
features = ["serde"]
