#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        # 移除zsh补全文件
        rm -f /usr/share/zsh/site-functions/_tuack-ng
        
        # 移除bash补全文件
        rm -f /usr/share/bash-completion/completions/tuack-ng
        
        # 移除fish补全文件
        rm -f /usr/share/fish/vendor_completions.d/tuack-ng.fish
        ;;
    
    upgrade|failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0